_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
architecture:
    value: mobilenet
batch_size:
    value: 20
epochs:
    value: 100
image_size:
    value: 100
learning_rate:
    value: 0.0005
loss:
    value: CrossEntropyWeighted
optimizer:
    value: Adam
